mysite/blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    # post views
    path("", views.post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path(
        "<int:post_id>/share/",
        views.post_share,
        name="post_share",
    ),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from blog.sitemaps import PostSitemap, TagSitemap
from django.views.generic import TemplateView

sitemaps = {
    "posts": PostSitemap,
    "tags": TagSitemap,
}
urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

mysite/blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=255)
    slug = models.SlugField(
        max_length=250,
        unique_for_date="publish",
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="blog_posts",
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.DRAFT,
    )
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "blog:post_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ],
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(
                fields=["created"],
            )
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

mysite/blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea,
    )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from django.contrib.postgres.search import (SearchQuery, SearchRank,
                                            SearchVector, TrigramSimilarity)
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST
from taggit.models import Tag

from .forms import CommentForm, EmailPostForm, SearchForm
from .models import Post


def post_share(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED,
    )
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (
                f"{cd['name']} ({cd['email']}) " f"recommends you read {post.title}"
            )
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}'s comments: {cd['comments']}"
            )
            send_mail(
                subject=subject,
                message=message,
                from_email=None,
                recipient_list=[cd["to"]],
            )
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request,
        "blog/post/share.html",
        {
            "form": form,
            "post": post,
            "sent": sent,
        },
    )


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Pagination
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get("page", 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    return render(
        request,
        "blog/post/list.html",
        {
            "posts": posts,
            "tag": tag,
        },
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids,
    ).exclude(id=post.id)

    similar_posts = similar_posts.annotate(
        same_tags=Count("tags"),
    ).order_by(
        "-same_tags", "publish"
    )[:4]

    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "form": form,
            "similar_posts": similar_posts,
        },
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED,
    )

    comment = False

    form = CommentForm(data=request.POST)

    if form.is_valid():
        # Stworzenie komentarza bez zapisywania do bazy danych
        comment = form.save(commit=False)
        # przypisanie posta do komentarza
        comment.post = post
        comment.save()

    return render(
        request,
        "blog/post/comment.html",
        {
            "post": post,
            "comment": comment,
            "form": form,
        },
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            results = (
                Post.published.annotate(
                    similarity=TrigramSimilarity("title", query),
                )
                .filter(similarity__gt=0.1)
                .order_by("-similarity")
            )

    return render(
        request,
        "blog/post/search.html",
        {
            "form": form,
            "query": query,
            "results": results,
        },
    )

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,700;1,400&family=Sour+Gummy:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <!-- favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
    <!-- font awesome -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <div class="row">
      <div class="col-md-6 mx-auto order-2 order-md-1 p-5">
        {% block content %}
        {% endblock %}
      </div>
      <div class="col-md-4 order-1 order-md-2 bg-light text-md-start text-center p-5">
        <h2 class="display-5 fw-bold">
          My blog
          <i class="fas fa-star"></i>
          <hr>
        </h2>
        <p class="primary">
          This is my blog.
          I've written {% total_post %} posts so far.
        </p>
        <p>
          <a href="{% url 'blog:post_feed' %}">
            <i class="fa-solid fa-rss me-1"></i>
            Subscribe to my RSS feed
          </a>
        </p>
        <h3 class="mb-4">Latest posts</h3>
        {% show_latest_posts 3 %}
        <h3 class="my-4">Most commented posts</h3>
        <ul class="list-group">
          {% get_most_commented_posts 3 as most_commented_posts %}
          {% for post in most_commented_posts %}
            <li class="list-group-item">
              <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock title %}

{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p>
      <a href="{{ post.get_absolute_url }}">
        Back to the post
      </a>
    </p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock content %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
  <h1 class="text-primary">{{ post.title }}</h1>
  <hr>
  <p>
    <span class="text-primary fw-bold">Tags:</span>
    {% for tag in post.tags.all %}
      <a href="{% url "blog:post_list_by_tag" tag.slug %}">
        {{ tag.name }}
      </a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
  </p>
  <p class="fst-italic text-secondary">
    Published {{ post.publish }} by <span class="text-primary">{{ post.author }}</span>
  </p>
  {{ post.body|markdown }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      Share this post
    </a>
  </p>

  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}
  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="card my-4">
      <div class="card-header">
        <span class="fst-italic text-secondary">
          Comment {{ forloop.counter }} by <span class="text-primary">{{ comment.name }}</span>
          {{ comment.created }}
        </span>
      </div>
      <div class="card-body">
        {{ comment.body }}
      </div>
    </div>
  {% empty %}
    <p>There are no comments.</p>
  {% endfor %}
  {% include "blog/post/includes/comment_form.html" %}
{% endblock content %}

mysite/blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
  {% csrf_token %}

  <div class="mb-3">
    <input
      type="text"
      class="form-control bg-light"
      name="{{ form.name.html_name }}"
      value="{{ form.name.value|default_if_none:'' }}"
      id="{{ form.name.id_for_label }}"
      placeholder="Enter your name">
  </div>

  <div class="mb-3">
    <input
      type="email"
      class="form-control bg-light"
      name="{{ form.email.html_name }}"
      value="{{ form.email.value|default_if_none:'' }}"
      id="{{ form.email.id_for_label }}"
      placeholder="Enter your email">
  </div>

  <div class="mb-3">
    <textarea
      class="form-control bg-light"
      name="{{ form.body.html_name }}"
      id="{{ form.body.id_for_label }}"
      placeholder="Enter your comment"></textarea>
  </div>
  <div class="d-grid gap-2">
    <input type="submit" value="Add comment" class="btn btn-primary text-white">
  </div>
</form>

mysite/blog/templates/blog/post/latest_posts.html
<ul class="list-group">
  {% for post in  latest_posts %}
    <li class="list-group-item">
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </li>
  {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>My blog</h1>
  <hr>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p>
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug%}">
          {{ tag.name }}
        </a>{% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p>
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
    <hr>
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock content %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock title %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4>
        <a href="{{ post.get_absolute_url }}">
          {{ post.title }}
        </a>
      </h4>
      {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p>
      <a href="{% url "blog:post_search" %}">
        Search again
      </a>
    </p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock content %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock title %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <h1 class="text-primary">Share "{{ post.title }}" by e-mail</h1>
          <hr>
          <form method="post">
            {% csrf_token %}

            <div class="mb-3">
              <input
                type="text"
                class="form-control bg-light"
                name="{{ form.name.html_name }}"
                placeholder="Your Name">
            </div>

            <div class="mb-3">
              <input
                type="email"
                class="form-control bg-light"
                name="{{ form.email.html_name }}"
                placeholder="Your Email">
            </div>

            <div class="mb-3">
              <input
                type="email"
                class="form-control bg-light"
                name="{{ form.to.html_name }}"
                placeholder="Recipient's Email">
            </div>

            <div class="mb-3">
              <textarea
                class="form-control bg-light"
                name="{{ form.comments.html_name }}"
                placeholder="Add a comment (optional)"></textarea>
            </div>

            <div class="d-grid gap-2">
              <input type="submit" value="Send e-mail" class="btn btn-primary text-white">
            </div>

          </form>
        </div>
      </div>
    </div>

  {% endif %}
{% endblock content %}

mysite/blog/templates/home.html
{% extends "blog/base.html" %}

{% block title %}Welcome to my Blog site{% endblock title %}

{% block content %}
  <div class="container">
    <h1 class="display-1 fw-bold text-primary text-center text-uppercase">Welcome to my Blog</h1>
    </div>
{% endblock %}

mysite/blog/templates/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    <!-- Poprzednia strona -->
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1">First</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">First</span>
      </li>
      <li class="page-item disabled">
        <span class="page-link">Previous</span>
      </li>
    {% endif %}

    <!-- Numery stron -->
    {% for num in page.paginator.page_range %}
      {% if num == page.number %}
        <li class="page-item active" aria-current="page">
          <span class="page-link">{{ num }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}

    <!-- Następna strona -->
    {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page.paginator.num_pages }}">Last</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link">Next</span>
      </li>
      <li class="page-item disabled">
        <span class="page-link">Last</span>
      </li>
    {% endif %}
  </ul>
</nav>